# Generated by Django 2.0.3 on 2018-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_profile_proj'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(to='index.Profile'),
        ),
    ]
