# Generated by Django 2.0.3 on 2018-03-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AlterField(
            model_name='project',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Profile'),
        ),
    ]
