# Generated by Django 2.0.3 on 2018-03-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.project'),
            preserve_default=False,
        ),
    ]
