# Generated by Django 2.0.3 on 2018-03-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_profile_proj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proj',
        ),
    ]
