# Generated by Django 2.0.3 on 2018-03-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_profile_proj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
