# Generated by Django 2.0.3 on 2018-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180320_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_confirmed',
            new_name='email_id',
        ),
    ]
